MERGE 
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(1, 'G');

MERGE 
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(2, 'PG');

MERGE
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(3, 'PG-13');

MERGE
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(4, 'R');

MERGE
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(5, 'NC-17');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(1, 'Комедия');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(2, 'Драма');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(3, 'Мультфильм');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(4, 'Триллер');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(5, 'Документальный');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(6, 'Боевик');


insert into FILMS (FILM_NAME, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA_RATING_FK, FILM_DESCRIPTION)
values  ('Фильм1', '2020-01-01', 101, 1, '1');

insert into FILMS (FILM_NAME, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA_RATING_FK, FILM_DESCRIPTION)
values  ('Фильм2', '2021-01-01', 102, 2, '2');

insert into FILMS (FILM_NAME, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA_RATING_FK, FILM_DESCRIPTION)
values  ('Фильм3', '2022-01-01', 103, 3, '3');

insert into FILMS (FILM_NAME, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA_RATING_FK, FILM_DESCRIPTION)
values  ('Фильм4', '2023-01-01', 104, 4, '4');

insert into FILMS (FILM_NAME, FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA_RATING_FK, FILM_DESCRIPTION)
values  ('Фильм5', '2024-01-01', 105, 5, '5');

insert into USERS (USER_LOGIN, USER_NAME, USER_EMAIL, USER_BIRTHDAY) 
values ('login1', 'name1', 'email1@yandex.ru', '2001-01-01');

insert into USERS (USER_LOGIN, USER_NAME, USER_EMAIL, USER_BIRTHDAY) 
values ('login2', 'name2', 'email2@yandex.ru', '2002-01-01');

insert into USERS (USER_LOGIN, USER_NAME, USER_EMAIL, USER_BIRTHDAY) 
values ('login3', 'name3', 'email3@yandex.ru', '2003-01-01');

insert into USERS (USER_LOGIN, USER_NAME, USER_EMAIL, USER_BIRTHDAY) 
values ('login4', 'name4', 'email4@yandex.ru', '2004-01-01');

insert into USERS (USER_LOGIN, USER_NAME, USER_EMAIL, USER_BIRTHDAY) 
values ('login5', 'name5', 'email5@yandex.ru', '2005-01-01');
