MERGE 
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(1, 'G');

MERGE 
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(2, 'PG');

MERGE
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(3, 'PG-13');

MERGE
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(4, 'R');

MERGE
	INTO
	MPA_RATINGS (MPA_RATING_ID_PK, MPA_RATING_NAME)
VALUES(5, 'NC-17');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(1, 'Комедия');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(2, 'Драма');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(3, 'Мультфильм');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(4, 'Триллер');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(5, 'Документальный');

MERGE
	INTO
	GENRES (GENRE_ID_PK, GENRE_NAME)
VALUES(6, 'Боевик');